# Generated by Django 5.1.4 on 2024-12-17 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aPedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lineapedido',
            table='aLineapedidos',
        ),
        migrations.AlterModelTable(
            name='pedido',
            table='aPedidos',
        ),
    ]
