# Generated by Django 5.1.4 on 2024-12-18 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aPedidos', '0002_alter_lineapedido_table_alter_pedido_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineapedido',
            old_name='pedido_id',
            new_name='pedido',
        ),
        migrations.RenameField(
            model_name='lineapedido',
            old_name='producto_id',
            new_name='producto',
        ),
    ]
